<?php
return [
    'deleted' => 1,
    'active' => 0,
    'numPerPage' => 10,
    'currency' => [
        '1' => 'USD',
        '2' => 'GBP',
        '3' => 'PLN',
        '4' => 'BAHT',
        '5' => 'EURO',
        '6' => 'IDR',
        '7' => 'AUD',
        '8' => 'MXN',
        '9' => 'COP',
        '10' => 'RON',
        '11' => 'PHP',
        '12' => 'BRL',
        '13' => 'PEN',
        '14' => 'MYR',
    ],
    'status' => [
        '0' => 'Active',
        '1' => 'Disabled',
        '2' => 'Past due',
    ],
    'TEMP_DIR' => 'public/tmp/',
    'PATH_UPLOAD' => 'public/uploads/',
    'AVATAR_DIR' => 'storage/uploads/',
];
